//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Project_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorInfo
    {
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Company { get; set; }
        public string Visiting { get; set; }
        public string ID_Type { get; set; }
        public string ID_Num { get; set; }
        public string Vehicle_Num { get; set; }
        public string Contact_num { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public System.DateTime Time { get; set; }
    }
}
